### ISSUE TITLE
No Metadata Exception when "emitDecoratorMetadata: true"

### ISSUE THREAD

**Issue by aklinker1** [szokodiakos/typegoose#187]
There appears to be an issue with decorators (or I have something wrong with babel 7). Here's the stack-trace for the basic example given:

```
Error: There is no metadata for the "name" property.Check if emitDecoratorMetadata is enabled in tsconfig.jsonor check if you've declared a sub docum
ent's class after usage.
    at /Users/apklinker/Programming/Personal/typegoose issue/node_modules/typegoose/src/prop.ts:182:11
    at /Users/apklinker/Programming/Personal/typegoose issue/index.ts:31:418
    at Array.reduce (<anonymous>)
    at _applyDecoratedDescriptor (/Users/apklinker/Programming/Personal/typegoose issue/index.ts:31:375)
    at Object.<anonymous> (/Users/apklinker/Programming/Personal/typegoose issue/index.ts:57:41)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module._compile (/Users/apklinker/Programming/Personal/typegoose issue/node_modules/pirates/lib/index.js:83:24)    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.newLoader [as .ts] (/Users/apklinker/Programming/Personal/typegoose issue/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at Object.<anonymous> (/Users/apklinker/Programming/Personal/typegoose issue/node_modules/@babel/node/lib/_babel-node.js:224:23)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
```

And here are other relevant files.

**index.ts**
```typescript
import { prop, Typegoose } from 'typegoose';
import mongoose from 'mongoose';

mongoose.connect('mongodb://localhost:27017/test');

class User extends Typegoose {
    @prop()
    name?: string;
}

const UserModel = new User().getModelForClass(User);

// UserModel is a regular Mongoose Model with correct types
(async () => {
    const u = new UserModel({ name: 'JohnDoe' });
    await u.save();
    const user = await UserModel.findOne();

    // prints { _id: 59218f686409d670a97e53e0, name: 'JohnDoe', __v: 0 }
    console.log(user);
})();
```

**tsconfig.json**
```json
{
  "compilerOptions": {    
    "target": "es2018",
    "module": "commonjs",
    "declaration": true,
    "outDir": "build",
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
  }
}
```

**.babelrc**
```json
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-typescript"
    ],
    "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        ["@babel/plugin-proposal-class-properties", { "loose": true }]
    ]
}
```

**package.json**
```json
{
  "name": "imdb-api",
  "version": "0.1.0",
  "scripts": {
    "start": "babel-node --extensions '.ts' index.ts"
  },
  "devDependencies": {
    "@babel/cli": "7.0.0-beta.49",
    "@babel/core": "^7.0.0",
    "@babel/node": "^7.0.0-beta.52",
    "@babel/plugin-proposal-class-properties": "7.0.0-beta.49",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/preset-env": "7.0.0-beta.49",
    "@babel/preset-typescript": "7.0.0-beta.49",
    "@types/mongoose": "^5.2.0",
    "@types/node": "^10.5.2",
    "typescript": "2.9.1"
  },
  "dependencies": {
    "mongoose": "^5.2.1",
    "reflect-metadata": "^0.1.12",
    "typegoose": "^5.2.1"
  }
}
```

**Comment by darajorjor** [comment]
I have the same issue

**Comment by semiautomatix** [comment]
Yes, seems to be a problem. Guess I'll have to do without typegoose, for now.

**Comment by ShabanGomaa** [comment]
I have the same issue

**Comment by zachary-volpi** [comment]
multiple resolvable problem here.

1. Using `@babel/preset-typescript` won't read the `tsconfig.json` file
2.  @babel/preset-typescript just strip all ts related config (in our case the decorator without keeping metadata about them)

adding `babel-plugin-transform-typescript-metadata` resolved it for me.
it should be defined as first !

```
  plugins: [
    'babel-plugin-transform-typescript-metadata',
    ['@babel/plugin-proposal-decorators', { 'legacy': true }],
    ['@babel/plugin-proposal-class-properties', { 'loose': true }]
  ]
```

**Comment by aklinker1** [comment]
@zachary-volpi that worked for me too.

Since I posted this I have stopped using Babel and just use the `tsc` to transpile my code, which also worked.

**Comment by zachary-volpi** [comment]
@aklinker1 i would love to see your configuration. If you could kindly share it here :)

**Comment by aklinker1** [comment]
@zachary-volpi Nothing special. If you follow the [Basic Usage](https://github.com/szokodiakos/typegoose#basic-usage) section of the README, and these dependencies, it builds and executes. I just refuse to use babel anymore because it's so difficult to work with, and just strips the types anyways. Kinda defeats the purpose of TS in the first place.

```json
// package.json
{
  "name": "typegoose-example",
  "scripts": {
    "build": "tsc -p .",
    "start": "node build/index.js",
    "start:dev": "yarn build && yarn start"
  },
  "dependencies": {
    "mongoose": "^5.5.6",
    "typegoose": "^5.6.0"
  },
  "devDependencies": {
    "@types/mongoose": "^5.3.27",
    "typescript": "^3.4.5"
  }
}
```

```ts
// index.ts
import { prop, Typegoose } from 'typegoose';
import mongoose from 'mongoose';

mongoose.connect(
    '<db-url>',
    { useNewUrlParser: true }
);

class User extends Typegoose {
    @prop() username?: string;
}
const UserModel = new User().getModelForClass(User);

(async () => {
    const u = new UserModel({ username: 'aklinker1' });
    await u.save();
    const user = await UserModel.findOne();

    console.log(user);
})();
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "outDir": "./build",
    "strict": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  }
}
```

**Comment by zachary-volpi** [comment]
@aklinker1 thanks for the response,
I was talking about your ts-loader config ;)

**Comment by aklinker1** [comment]
@zachary-volpi I don't use webpack, just the typscript compiler.

**Comment by patarapolw** [comment]
I have a problem too. May be it has something to do with `tsconfig.json`, so I created `tsconfig.backend.json` with

```json
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "target": "esnext",
        "module": "commonjs",
        "outDir": "./build",
        "strict": true,
        "esModuleInterop": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
    },
    "exclude": [
        "src/frontend"
    ]
}
```

It seems that the target has to be `commonjs` for some reasons.
