### ISSUE TITLE
TypeError: Invalid schema configuration: `True` is not a valid type at path `required`.

### ISSUE THREAD

**Issue by CasterKKK** [szokodiakos/typegoose#238]
---- New Info ----

I found that it is because `arrayProp`(in another word, Array<T>) cannot deal with `required: true`, please fix this error as soon as possible.

Right now, `public array?: ArrayItem[];` cannot be set as `required: true`, or you could face the error as I did

---- Old Question ----
Here is a deadly simple class:
``` typescript
export class MedicalAccountPersonItem {
  @prop({required: true})
  public personName: string;
  @prop({required: true, min: 0.0})
  public outcome: number;
  @prop({required: true, min: 0.0})
  public remaining: number;
}

export class MedicalAccount extends Typegoose {
  @prop({required: true, index: true})
  public id: string;
  @prop({required: true, ref: DetailedAccount})
  public detailedAccount: Ref<DetailedAccount>;
  @prop({required: true, index: true})
  public timestamp: Date;
  @prop({required: true})
  public item: string;
  @prop({required: true, min: 0.0})
  public unitPrice: number;
  @prop({required: true, min: 0.0})
  public unitNumber: number;
  @arrayProp({required: true, items: MedicalAccountPersonItem})
  public personItems?: MedicalAccountPersonItem[];

  @prop()
  get sumOutcome(): number {
    return this.personItems ? this.personItems.map((p) => p.outcome).reduce((a, b) => a + b) : 0;
  }

  @prop()
  get sumRemaining(): number {
    return this.personItems ? this.personItems.map((p) => p.remaining).reduce((a, b) => a + b) : 0;
  }
}

export const MedicalAccountModel = new MedicalAccount().getModelForClass(MedicalAccount);
```

But I will get 
```/Users/ukonnra/Workspaces/DesktopWorkspace/private-accounting/node_modules/mongoose/lib/schema.js:749
    throw new TypeError(`Invalid schema configuration: \`${name}\` is not ` +
          ^
TypeError: Invalid schema configuration: `True` is not a valid type at path `required`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
```
when `import {DetailedAccountModel} from "../../model";`. And if I remove ALL the `required: true`, I can save this model to Mongo correctly.

As you can see in the error info, `required: true` has been compiled to `True`, which is really weird...

I have no idea where is wrong, please help...

**Comment by singhsoldier13** [comment]
+1

**Comment by krouw** [comment]
I'm remove `required: true` from array properties (personItems in this case) and I solved my problem

**Comment by Im10Anish** [comment]
include this in schema:
    location: {
        type: { type: String },
		coordinates: [],
		required: true
	},
now get to know, because of required: true it's giving me this error, please help..

**Comment by RizkyArifNur** [comment]
i found this error too, when set ```@prop({required: true})```

**Comment by hasezoey** [comment]
Can Confirm
Error:
```
/projects/testing/node_modules/mongoose/lib/schema.js:820
    throw new TypeError(`Invalid schema configuration: \`${name}\` is not ` +
          ^
TypeError: Invalid schema configuration: `True` is not a valid type at path `required`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (/projects/testing/node_modules/mongoose/lib/schema.js:820:11)
    at Schema.path (/projects/testing/node_modules/mongoose/lib/schema.js:596:27)
    at Schema.add (/projects/testing/node_modules/mongoose/lib/schema.js:437:12)
    at new Schema (/projects/testing/node_modules/mongoose/lib/schema.js:117:10)
    at Schema.interpretAsType (/projects/testing/node_modules/mongoose/lib/schema.js:770:29)
    at Schema.path (/projects/testing/node_modules/mongoose/lib/schema.js:596:27)
    at Schema.add (/projects/testing/node_modules/mongoose/lib/schema.js:437:12)
    at new Schema (/projects/testing/node_modules/mongoose/lib/schema.js:117:10)
    at DummyType.Typegoose.buildSchema (/projects/testing/node_modules/typegoose/src/typegoose.ts:72:71)
    at DummyType.Typegoose.setModelForClass (/projects/testing/node_modules/typegoose/src/typegoose.ts:44:20)
    at DummyType.Typegoose.getModelForClass (/projects/testing/node_modules/typegoose/src/typegoose.ts:30:12)
    at Object.<anonymous> (/projects/testing/src/app.ts:20:36)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
```

Full Dummy Code to Reproduce:
```ts
import { ObjectID } from "bson";
import * as mongoose from "mongoose";
import { arrayProp, prop, Typegoose } from "typegoose";

class DummyItem {
    @prop({ required: true })
    public dummy!: string;
}

class DummyType extends Typegoose {
    @prop({ required: true, index: true })
    public id!: ObjectID;

    @arrayProp({ required: true, items: DummyItem })
    public personItems!: DummyItem[];
}

const DummyModel = new DummyType().getModelForClass(DummyType);

(async () => {
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify238",
        user: "test",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    await new DummyModel({ } as DummyType).save();
})();

```

**Comment by hasezoey** [comment]
#193 might be related, or this is even a duplicate

**Comment by hasezoey** [comment]
#302 seems to have fixed this, at least when i try to execute the reproduce code, it dosnt error anymore

so i think this can be closed
@Ben305
