### ISSUE TITLE
Enum not working

### ISSUE THREAD

**Issue by ChrisLahaye** [szokodiakos/typegoose#286]
Hello,

Enums are not working for me. I get the following error:

```
/home/chris/lem/node_modules/typegoose/lib/prop.js:94
    var instance = new Type();
                   ^

TypeError: Type is not a constructor
    at baseProp (/home/chris/lem/node_modules/typegoose/src/prop.ts:154:20)
    at /home/chris/lem/node_modules/typegoose/src/prop.ts:223:3
    at /home/chris/lem/src/app/models/user.ts:18:410
    at Array.reduce (<anonymous>)
    at _applyDecoratedDescriptor (/home/chris/lem/src/app/models/user.ts:18:367)
    at Object.<anonymous> (/home/chris/lem/src/app/models/user.ts:87:20)
```

With the following code:
```
enum UserType {
  Admin = 'admin',
  Guest = 'guest',
}

export class User extends Typegoose {
  @prop({ enum: UserType })
  public type: UserType;
}
```

This is my typescript config:
```
{
	"compilerOptions": {
		/* Allow default imports from modules with no default export.  */
		"allowSyntheticDefaultImports": true,
		/* Specify ECMAScript target version */
		"target": "esnext",
		/* Specify module code generation */
		"module": "esnext",
		/* Determine how modules get resolved */
		"moduleResolution": "node",
		/* Emit design-type metadata for decorated declarations in source. */
		"emitDecoratorMetadata": true,
		/* Enables experimental support for ES decorators. */
		"experimentalDecorators": true,
	},
	"include": [
		"src"
	]
}
```

Any idea how I can fix this? 

Thank you!

**Comment by hasezoey** [comment]
Obvious Question: What is `Type`?
-> is it `const Type = new User().getModelForClass(User);`?

aside from this, i cant reproduce it

Full Reproduce Code i used:
```ts
import * as mongoose from "mongoose";
import "source-map-support/register";
import { prop, Typegoose } from "typegoose";

enum DummyEnum {
    on = "on",
    off = "off"
}

class DummyType extends Typegoose {
    @prop({ required: true, enum: DummyEnum })
    public enumProp!: DummyEnum;
}

const DummyModel = new DummyType().getModelForClass(DummyType);

(async () => {
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify286",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const instance = await new DummyModel();
    instance.enumProp = DummyEnum.off;
    await instance.save();
})();
```

**Comment by ChrisLahaye** [comment]
@hasezoey Thank you for having a look, that is well appreciated.

I tried your example and get the same error. It might be related to my babel config:

```
{
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ],
  "presets": [
    ["@babel/preset-env", { "targets": { "node": "10" } }],
    "@babel/typescript"
  ]
}
```

Do you perhaps have any idea what I could try.

**Comment by hasezoey** [comment]
i dont know babel, but when you just use Node 10 (only) as the output, you should use tsc and compile with es6

the tsconfig i use (for es2018 ~ Node 11~12)
```json
{
    "compileOnSave": true,
    "typeAcquisition": {
        "enable": true
    },
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declarationMap": true,
        "baseUrl": ".",
        "paths": { "*": ["types/*"] },
        "outDir": "tsbuild/",
        "declarationDir": "tsdec/",
        "moduleResolution": "node",
        "target": "es2018",
        "module": "commonjs",
        "newLine": "LF",
        "sourceMap": true,
        "removeComments": true,
        "strict": true,
        "allowUnreachableCode": false,
        "pretty": true,
        "declaration": true,
        "lib": [
            "es2018"
        ]
    },
    "include": [
        "src/**/*"
    ]
}
```

**Comment by ChrisLahaye** [comment]
Thanks for the tip, fixed after using tsc over babel

**Comment by gimyboya** [comment]
@hasezoey I am having the same error described here. any workaround?

here is my `tsconfig.json`:

```json
{
  "typeAcquisition": {
    "enable": true
  },
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "declarationMap": true,
    "removeComments": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2018",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "lib": ["es2018"],
    "incremental": true,
    "tsBuildInfoFile": "./dist/.buildcache"
  },
  "exclude": ["node_modules", "test", "dist", "**/*spec.ts"]
}

```

**Comment by hasezoey** [comment]
@gimyboya because it is a "same" issue and this issue is not *too* old, please paste your code, with the error OR bake the error as a comment into the code, otherwise we cant help you

**Comment by gimyboya** [comment]
Ok, I fixed the problem by doing the following:

I changed my prop from this:
```ts
@ArrayProperty({ required: true, items: Roles })
@Field(type => [Roles])
readonly roles: Roles[];
```

to this:
```ts
@ArrayProperty({ required: true, items: String, enum: Roles })
@Field(type => [Roles])
readonly roles: Roles[];
```

**Comment by gimyboya** [comment]
@hasezoey Thanks for the fast reply I still have a question about enums.

can't we use numeric enums at all?

such as this:

```ts
export enum Privileges {
  OWNER = 0,
  LIST,
  MANAGE,
}
```

I find myself alwayse forced to convert it to a string enum

**Comment by hasezoey** [comment]
@gimyboya your issue is not a typegoose issue
[look here for more help](https://stackoverflow.com/questions/42303758/mongoose-enum-number)
