### ISSUE TITLE
arrayProp default

### ISSUE THREAD

**Issue by ChrisLahaye** [szokodiakos/typegoose#301]
Hello,

According to mongoose documentation an array is always initialized as an empty array unless specified. This behavior can be overwritten by using the default `default: (): any => null` although this does not seem to work in typegoose.

```
TypeError: Invalid schema configuration: `Default` is not a valid type at path `default`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (/home/chris/project/node_modules/mongoose/lib/schema.js:820:11)
    at Schema.path (/home/chris/project/node_modules/mongoose/lib/schema.js:596:27)
    at Schema.add (/home/chris/project/node_modules/mongoose/lib/schema.js:437:12)
    at new Schema (/home/chris/project/node_modules/mongoose/lib/schema.js:117:10)
    at Schema.interpretAsType (/home/chris/project/node_modules/mongoose/lib/schema.js:770:29)
    at Schema.path (/home/chris/project/node_modules/mongoose/lib/schema.js:596:27)
    at Schema.add (/home/chris/project/node_modules/mongoose/lib/schema.js:437:12)
    at new Schema (/home/chris/project/node_modules/mongoose/lib/schema.js:117:10)
    at Payment.Typegoose.buildSchema (/home/chris/project/node_modules/typegoose/lib/typegoose.js:61:84)
    at Payment.Typegoose.setModelForClass (/home/chris/project/node_modules/typegoose/lib/typegoose.js:37:24)
    at Payment.Typegoose.getModelForClass (/home/chris/project/node_modules/typegoose/lib/typegoose.js:25:18)
    at Object.<anonymous> (/home/chris/project/dist/app/models/payment.js:280:33)
```

How can I initialize an array as undefined?

Thank you

**Comment by hasezoey** [comment]
is #296 Related?

**Comment by hasezoey** [comment]
otherwise, why would you want to make an array "undefined" / "null"?

anyway, i made an example below, but because "undefined" / "null" is not normal to use, you must make your own validation for this type:
```ts
import * as mongoose from "mongoose";
import { arrayProp, Typegoose } from "./typegoose/src/typegoose";

class Dummy extends Typegoose {
    @arrayProp({ required: true, items: String, default: undefined })
    public dummy1!: string[];
}

const DummyModel = new Dummy().getModelForClass(Dummy);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify301",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    await new DummyModel().save();

    await mongoose.disconnect();
})();
```

**Comment by ChrisLahaye** [comment]
Thank you for your reply!

Not sure if #296 is related. In his case, I think he has to wrap the default value into a function.

The whole idea of NoSQL is to permit dynamic schemas. We prefer fields to be undefined/missing if they are not applicable to the document. Besides, null/defined are perfectly legit values as they have their own semantic meaning, similarly as NULL does in SQL.

It seems like `default: undefined` is only working when `items: String`, not when using `item: ClassName`. I get the error `TypeError: Invalid value for schema path default` when using `default: undefined` instead of what is suggested by the docs (`default: () => null`)

**Comment by ChrisLahaye** [comment]
```
class Dummy extends Typegoose {
    @prop({ default: 'test', required: true })
    public name: string;

    @arrayProp({ items: Transfer })
    public dummy1: Transfer[];
}

const DummyModel = new Dummy().getModelForClass(Dummy);
DummyModel.create({}).then(z => { z.save();  console.info(z); });
```

```
class Dummy extends Typegoose {
    @prop({ default: 'test', required: true })
    public name: string;

    @arrayProp({ items: Transfer })
    public dummy1: Transfer[];
}

const DummyModel = new Dummy().getModelForClass(Dummy);
DummyModel.create({}).then(z => { z.save();  console.info(z); });
```

See the empty array

**Comment by hasezoey** [comment]
also from what i have tested, this works:
(Note: removed the required tag, then it is not there anymore)
```ts
import * as mongoose from "mongoose";
import { arrayProp, prop, Typegoose } from "./typegoose/src/typegoose";

class Someotherclass {
    @prop({})
    public something: string;
}
class Dummy extends Typegoose {
    @prop({ required: true , default: "hello" })
    public name!: string;

    @arrayProp({ items: Someotherclass, default: undefined })
    public dummy1!: Someotherclass[];
}

const DummyModel = new Dummy().getModelForClass(Dummy);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify301",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    await new DummyModel().save();

    await mongoose.disconnect();
})();
```

**Comment by ChrisLahaye** [comment]
Your example gives me:

```
130 chris@arch ~/project (git)-[v2] % node dist/bin/test.js                                                                                                               :(/home/chris/project/node_modules/mongoose/lib/schema.js:414      throw new TypeError('Invalid value for schema path `' + prefix + key + '`');
      ^

TypeError: Invalid value for schema path `default`
    at Schema.add (/home/chris/project/node_modules/mongoose/lib/schema.js:414:13)
    at new Schema (/home/chris/project/node_modules/mongoose/lib/schema.js:117:10)
    at Schema.interpretAsType (/home/chris/project/node_modules/mongoose/lib/schema.js:770:29)
    at Schema.path (/home/chris/project/node_modules/mongoose/lib/schema.js:596:27)
    at Schema.add (/home/chris/project/node_modules/mongoose/lib/schema.js:437:12)
    at new Schema (/home/chris/project/node_modules/mongoose/lib/schema.js:117:10)
    at Dummy.Typegoose.buildSchema (/home/chris/project/node_modules/typegoose/lib/typegoose.js:61:84)
    at Dummy.Typegoose.setModelForClass (/home/chris/project/node_modules/typegoose/lib/typegoose.js:37:24)
    at Dummy.Typegoose.getModelForClass (/home/chris/project/node_modules/typegoose/lib/typegoose.js:25:18)
    at Object.<anonymous> (/home/chris/project/dist/bin/test.js:30:32)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by hasezoey** [comment]
sorry, try [this version of typegoose](https://gitlab.com/hasezoey/typegoose)
it implements some fixes

**Comment by ChrisLahaye** [comment]
@hasezoey there it works. Do you plan on contributing the respective commit here?

**Comment by hasezoey** [comment]
@ChrisLahaye i think not, because my (gitlab) version consists mostly of pull requests (i dont know wich one solved this here) and has a test rewrite + coding style "rewrite", and i dont think that i can so commit this here, 

maybe @Ben305 could take a look at it, and decide if it would be ok
