### ISSUE TITLE
using subdocuments causes "TypeError: Type is not a constructor"

### ISSUE THREAD

**Issue by haezl** [szokodiakos/typegoose#307]
Having two models, one as subdocument of the other, and both extend Typegoose the error is raised as soon as one tries to create an instance of the subdocument. However, using refrences, the code is working properly.

Comment Model:
```javascript
export class Comment extends Typegoose {
    @prop()
    public text: string;
}

const CommentModel = new Comment().getModelForClass(Comment);
export default CommentModel;
```

Post Model:
```javascript
export class Post extends Typegoose {
    @prop()
    public description: string;

    @arrayProp({ items: { name: "Comment" } })
    public comments: Comment[];
}

const PostModel = new Post().getModelForClass(Post);
export default PostModel;
```

Trying to add a comment to a post results in the Error: **TypeError: Type is not a constructor**
```javascript
        const comment = new CommentModel({
            text: args.text
        });
        await post.comments.push(comment);
        await post.save();
```

However, when Comment is used as a reference inside of Post, everything is working fine.

Updated Post Model to use references:
```javascript
export class Post extends Typegoose {
    @prop()
    public description: string;

    @arrayProp({ itemsRef: { name: "Comment" } })
    public comments: Ref<Comment>[];
}

const PostModel = new Post().getModelForClass(Post);
export default PostModel;
```

Any ideas on this?

**Comment by haezl** [comment]
I took a look into the source code, the error was raised by https://github.com/szokodiakos/typegoose/blob/master/src/prop.ts#L165

This seems kind of a workaround for me to get it working:

Updating the Post Model to use ObjectType instead of Comment
```javascript
    @arrayProp({ items: ObjectType })
    public comments: Comment[];
```

(Optionally) refactoring the Comment model to not extend Typegoose anymore:
```javascript
export class Comment {
    @prop({ required: true, trim: true, unique: true })
    public text: string;
}
```

Pushing the document directly, without instanciating a comment of type Comment: 
```javascript
await post.comments.push({
            text: args.text
        } as any);
```

Probably there is a nicer way doing this?

----------------------------------------------------------------

In case subdocument has any references --> creating those manually by importing `ObjectId` from the `mongodb` package works, even though this seems bit of a hack to me.

```javascript
        const result = await post.comments.push({
            text: args.text,
            user: new ObjectId(user._id)
        } as any);
```

Pasting the user directly would be cleaner (without the need of the `mongodb` package) however in this case the user would of course be flattened and stored as a subdocument instead of a reference:

```javascript
        const result = await post.comments.push({
            text: args.text,
            user: user
        } as any);
```

Is there a better way expressing it?

**Comment by hasezoey** [comment]
as far as i can tell, a subdocument shouldnt be an extend of Typegoose, but it shouldnt be an issue to still do it...
i will look into it

**Comment by hasezoey** [comment]
i dont know if this solves your issue, but i made an example
but it [requires this](https://gitlab.com/hasezoey/typegoose) because there are more fixes already implemented

```ts
import * as mongoose from "mongoose";
import { arrayProp, prop, Typegoose } from "./typegoose/src/typegoose";

class DummySub extends Typegoose {
    @prop({ required: true, default: "hello" })
    public something!: string;
}

class Dummy extends Typegoose {
    @arrayProp({ required: true, items: DummySub })
    public items!: DummySub[];
}

const DummyModel = new Dummy().getModelForClass(Dummy);
const DummySubModel = new DummySub().getModelForClass(DummySub);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify307",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    // create an parent with some dummys
    const tmp = await new DummyModel({ items: [await new DummySubModel({}), await new DummySubModel({})]});

    // create a child with modified value
    const tmpsub = await new DummySubModel({ something: "not hello2" } as DummySub);
    tmp.items.push(tmpsub);

    // save it
    await tmp.save();

    // find it to make sure everything works
    const found = await DummyModel.findById(tmp._id);
    // just to list them out
    found.items.forEach((v) => console.log(v.something));

    await mongoose.disconnect();
})();
```

**Comment by haezl** [comment]
Thanks a lot @hasezoey 

I've also got it working now with references

```javascript
import mongoose from "mongoose";
import { arrayProp, prop, Typegoose, Ref } from from "./typegoose/src/typegoose";

class User extends Typegoose {
    @prop({ required: true, default: "john@doe.com" })
    public email!: string;
}

class Comment extends Typegoose {
    @prop({ required: true, default: "hello" })
    public text!: string;

    @prop({ ref: User })
    public user: Ref<User>;
}

class Post extends Typegoose {
    @arrayProp({ required: true, items: Comment })
    public items!: Comment[];

    @prop({ ref: User })
    public user: Ref<User>;
}

const PostModel = new Post().getModelForClass(Post);
const CommentModel = new Comment().getModelForClass(Comment);
const UserModel = new User().getModelForClass(User);

(async () => {
    // mongoose.set("debug", true);
    await mongoose.connect(`mongodb://localhost:27017/typegoose`, {
        useNewUrlParser: true,
    });

    // create a dummy ref instance
    const user = await new UserModel({});
    const result = await user.save();
    console.log("result: ", JSON.stringify(result, null, 2));

    // create an parent
    const post = await new PostModel({ user });

    // create a child with modified value and set dummy ref
    const tmpsub = await new CommentModel({ something: "not hello2", user });
    post.items.push(tmpsub);

    // save it
    await post.save();

    // find it to make sure everything works
    const found = await PostModel.findById(post._id);
    // just to list them out
    found!.items.forEach((v) => console.log(v.text));

    await mongoose.disconnect();
})();
```

@hasezoey Do you also maintain the `typegoose` npm package?

**Comment by hasezoey** [comment]
> @hasezoey Do you also maintain the typegoose npm package?

no, im not a maintainer of this, otherwise i wouldn't have created another repo  

@szokodiakos is the repo owner
and @Ben305 is the one who currently maintains it
and mine, is just a fork, with some pull requests & test rewrites & coding style changes

**Comment by haezl** [comment]
@hasezoey: Thanks for the clarification.

Meanwhile I stumpled across the root cause for the issue. 
Its actually when two documents are referencing each other and has nothing to do with subdocuments.

Dummy.ts:
```javascript
import { prop, Typegoose, Ref } from "typegoose";
import { DummyRef } from "./DummyRef";

export class Dummy extends Typegoose {
    @prop({ ref: DummyRef })
    public myref: Ref<DummyRef>;
}
```
DummyRef.ts
```javascript
import { arrayProp, prop, Typegoose, Ref } from "typegoose";
import { Dummy } from "./Dummy";

export class DummyRef extends Typegoose {
    @prop({ required: true, default: "whatever" })
    public whatever: string;

    @arrayProp({ itemsRef: Dummy })
    public dummies: Ref<Dummy>[];
}
```

main.ts
```javascript
import mongoose from "mongoose";
import { Dummy } from "./src/Dummy";
import { DummyRef } from "./src/DummyRef";

const DummyModel = new Dummy().getModelForClass(Dummy);
const DummySubRef = new DummyRef().getModelForClass(DummyRef);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/typegoose`, {
        useNewUrlParser: true,
    });

    const myrefobject = await new DummySubRef({})

    // create an parent with a ref
    const tmp = await new DummyModel({ myref: myrefobject });

    // save it
    await tmp.save();

    await mongoose.disconnect();
})();
```
Error:
```
markus@marho:~/test1$ ts-node index.ts 
TypeError: Type is not a constructor
    at baseProp (/home/markus/test1/node_modules/typegoose/src/prop.ts:165:20)
    at /home/markus/test1/node_modules/typegoose/src/prop.ts:247:3
    at DecorateProperty (/home/markus/test1/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (/home/markus/test1/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (/home/markus/test1/src/DummyRef.ts:17:92)
    at /home/markus/test1/src/DummyRef.ts:9:5
    at Object.<anonymous> (/home/markus/test1/src/DummyRef.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module.m._compile (/home/markus/.nvm/versions/node/v12.3.0/lib/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.require.extensions.<computed> [as .ts] (/home/markus/.nvm/versions/node/v12.3.0/lib/node_modules/ts-node/src/in
```

I got this issue in my application as both posts and comments (which are subdocuments of the post) have a reference to a user - and a user also has an array of references to posts.

**Comment by haezl** [comment]
However if I change the line
```javascript
    @prop({ ref: DummyRef })
```
 to
```javascript
    @prop({ ref: { name: "DummyRef" } })
```
in Dummy.ts and do the same with DummyRef.ts my previous example is working.

**Comment by Laubeee** [comment]
I had the same issue, but somehow only when implementing a function that does a find on one Model but returns a different type (passed to the function as parameter, the idea is to aggregate some more info from other collections and return them in the original data object)
using `{ name: "ClassName" }` fixed it.
Using Typegoose 5.9.2
