### ISSUE TITLE
@plugin decorator not working unless you have one other @staticMethod

### ISSUE THREAD

**Issue by vogong** [szokodiakos/typegoose#58]
Using @Plugin without have in an @staticMethod leaves the schema.statics uninitialized.

**Comment by pgsfredda** [comment]
Hi @vogong,
please, can you post an example?

**Comment by vogong** [comment]
```
interface FindOrCreateResult<T> {
    created: boolean;
    doc: InstanceType<T>;
  }

@plugin(findOrCreate)
class User extends Typegoose {
    @prop()
    name?: string;

    // @staticMethod
    // static helloWorld(this: ModelType<User> & typeof User) {
    //   console.log("Hello WOrld");
    // }

    static findOrCreate: (condition: any) => Promise<FindOrCreateResult<User>>;
}
const model = new User().getModelForClass(User);

\\Mongoose connection and promise

connection.on('connected', () => {
    (async () => {
        var car = new model({ name: "user@domain.com" });
        await car.save();
    })();
});

```

**The above example fails to run with the following error unless you uncomment the static function and initialize statics**

typegoosetest\node_modules\mongoose-findorcreate\index.js:8
  schema.statics.findOrCreate = function findOrCreate(conditions, doc, options, callback) {
                              ^

TypeError: Cannot set property 'findOrCreate' of undefined
    at findOrCreatePlugin (typegoosetest\node_modules\mongoose-findorcreate\index.js:8:31)
    at Schema.plugin (typegoosetest\node_modules\typegoose\node_modules\mongoose\lib\schema.js:1208:3)
    at _.forEach (typegoosetest\node_modules\typegoose\lib\typegoose.js:40:25)
    at arrayEach (typegoosetest\node_modules\typegoose\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (typegoosetest\node_modules\typegoose\node_modules\lodash\lodash.js:9359:14)
    at User.getModelForClass (typegoosetest\node_modules\typegoose\lib\typegoose.js:39:19)
    at Object.<anonymous> (typegoosetest\dist\server\app.js:32:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by szokodiakos** [comment]
Hello. Thanks for posting this. There was a missing initializer in the code which is now handled properly in https://github.com/szokodiakos/typegoose/commit/f7706a31f2e28dda4392a1a794ce9d1f7452d277. I've tested this and it was working after the fix. Closing this one.
