### ISSUE TITLE
defining propArray as a type that extends typegoose results in an error

### ISSUE THREAD

**Issue by CoreParadox** [szokodiakos/typegoose#78]
```
_\node_modules\mongoose\lib\index.js:477
  if (schema.$globalPluginsApplied) {
                    
TypeError: Cannot read property '$globalPluginsApplied' of undefined
    at Mongoose._applyPlugins (_\node_modules\mongoose\lib\index.js:477:14)
    at Mongoose._applyPlugins (_\node_modules\mongoose\lib\index.js:487:10)
    at Mongoose.model (_\node_modules\mongoose\lib\index.js:396:10)
    at TestModel.setModelForClass (_\node_modules\typegoose\lib\typegoose.js:44:31)
    at TestModel.getModelForClass (_\node_modules\typegoose\lib\typegoose.js:20:18)
```

Setup looks like the following:

`export const TestModel = new Test().getModelForClass(Test, {existingConnection: mongoose});`

```
export class Test extends Typegoose {
    @prop({index:true})
    userId:string;
    @arrayProp({ items: Item})
    items?: Item[];
```
```
export class Item extends Typegoose {
    @prop({index:true})
    id:string;
    @prop()
    name: string;
}
```

using mongoose 4.13.6

**Comment by CoreParadox** [comment]
Looks like downgrading to mongoose 4.11.1 fixes this issue.
